spring:
  application:
    name: hoaxify

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hoaxifyDB
    username: root
    password: 

  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  profiles:
    active: dev


# ---------------- PROD PROFILE ----------------
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/hoaxify-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  mysql:
    console:
      enabled: false

hoaxify:
  upload-path: uploads-prod


# ---------------- DEV PROFILE ----------------
---
spring:
  config:
    activate:
      on-profile: dev

hoaxify:
  upload-path: uploads-dev


# ---------------- TEST PROFILE ----------------
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/hoaxifyDB_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

hoaxify:
 upload-path: uploads-test	
